version: "3.8"
services:
  seguridad:
    build:
      context: ./mssideimss-seguridad
      dockerfile: Dockerfile
    ports:
      - "4109:4109"
    container_name: mssideimss-seguridad

  catalogos:
    build:
      context: ./mssideimss-catalogos
      dockerfile: Dockerfile
    ports:
      - "4110:4110"
    container_name: mssideimss-catalogos

  devoluciones:
    build:
      context: ./mssideimss-contadores
      dockerfile: Dockerfile
    ports:
      - "4111:4111"
    container_name: mssideimss-contadores