version: "3.8"
services:
  seguridad:
    build:
      context: ./mssideimss-seguridad
      dockerfile: Dockerfile
    ports:
      - "4109:4109"
    container_name: mssideimss-seguridad

  catalogos:
    build:
      context: ./mssideimss-catalogos
      dockerfile: Dockerfile
    ports:
      - "4110:4110"
    container_name: mssideimss-catalogos

  contadores:
    build:
      context: ./mssideimss-contadores
      dockerfile: Dockerfile
    ports:
      - "4111:4111"
    container_name: mssideimss-contadores
    environment:  
      - SIDEIMSS_DOCUMENTOS_URL=http://documentos:4113/mssideimss-documentos/v1/cargarDocumento  
    depends_on:  
      - documentos  

  acuses:
    build:
      context: ./mssideimss-acuses
      dockerfile: Dockerfile
    ports:
      - "4112:4112"
    container_name: mssideimss-acuses

  documentos:
    build:
      context: ./mssideimss-documentos
      dockerfile: Dockerfile
    ports:
      - "4113:4113"
    container_name: mssideimss-documentos
      
