
package mx.gob.imss.catalogos.medioscontacto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Jws", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Jws {


    /**
     * 
     * @param rfc
     * @return
     *     returns mx.gob.imss.catalogos.medioscontacto.ArrayOfMedContactoRepreLegalDTOLiteral
     */
    @WebMethod(action = "http://www.openuri.org/recuperaMediosContacto")
    @WebResult(name = "listaMediosContacto", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "recuperaMediosContacto", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.catalogos.medioscontacto.RecuperaMediosContacto")
    @ResponseWrapper(localName = "recuperaMediosContactoResponse", targetNamespace = "http://www.openuri.org/", className = "mx.gob.imss.catalogos.medioscontacto.RecuperaMediosContactoResponse")
    public ArrayOfMedContactoRepreLegalDTOLiteral recuperaMediosContacto(
        @WebParam(name = "rfc", targetNamespace = "http://www.openuri.org/")
        String rfc);

}
