
package mx.gob.imss.catalogos.medioscontacto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JwsServiceSoapBindingQSService", targetNamespace = "http://www.openuri.org/", wsdlLocation = "http://osbserviciosdigitales.imss.gob.mx:80/DictamenService/MediosContacto?wsdl")
public class JwsServiceSoapBindingQSService
    extends Service
{

    private final static URL JWSSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException JWSSERVICESOAPBINDINGQSSERVICE_EXCEPTION;
    private final static QName JWSSERVICESOAPBINDINGQSSERVICE_QNAME = new QName("http://www.openuri.org/", "JwsServiceSoapBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://osbserviciosdigitales.imss.gob.mx:80/DictamenService/MediosContacto?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JWSSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION = url;
        JWSSERVICESOAPBINDINGQSSERVICE_EXCEPTION = e;
    }

    public JwsServiceSoapBindingQSService() {
        super(__getWsdlLocation(), JWSSERVICESOAPBINDINGQSSERVICE_QNAME);
    }

    public JwsServiceSoapBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JWSSERVICESOAPBINDINGQSSERVICE_QNAME, features);
    }

    public JwsServiceSoapBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, JWSSERVICESOAPBINDINGQSSERVICE_QNAME);
    }

    public JwsServiceSoapBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JWSSERVICESOAPBINDINGQSSERVICE_QNAME, features);
    }

    public JwsServiceSoapBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JwsServiceSoapBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Jws
     */
    @WebEndpoint(name = "JwsServiceSoapBindingQSPort")
    public Jws getJwsServiceSoapBindingQSPort() {
        return super.getPort(new QName("http://www.openuri.org/", "JwsServiceSoapBindingQSPort"), Jws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Jws
     */
    @WebEndpoint(name = "JwsServiceSoapBindingQSPort")
    public Jws getJwsServiceSoapBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.openuri.org/", "JwsServiceSoapBindingQSPort"), Jws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JWSSERVICESOAPBINDINGQSSERVICE_EXCEPTION!= null) {
            throw JWSSERVICESOAPBINDINGQSSERVICE_EXCEPTION;
        }
        return JWSSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
