server:
  port: ${SIDEIMSS_ACUSES_PORT}
jwt:
  secret: TExBVkVfTVVZX1NFQ1JFVEzE3Zmxu7BSGSJx72BSBXM 
spring:
  application:
    name: mssideimss-acuses
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${SIDEIMSS_DB_URL_2}
    username: ${SIDEIMSS_DB_USER_2}
    password: ${SIDEIMSS_DB_PASSWORD_2}
    hikari:
      minimum-idle: ${POOL_MINIMUM_IDLE}
      maximum-pool-size: ${POOL_MAX_SIZE}
      idle-timeout: ${POOL_IDLE_TIMEOUT}
      max-lifetime: ${POOL_LIFETIME}
      connection-timeout: ${POOL_CONNECTION_TIMEOUT}
      pool-name: sideimssPoolAcuses
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        proc:
          param_null_passing: true
management:
  endpoints:
    web:
      base-path: /mssideimss-acuses/v1/actuator
      exposure:
        include: health
  endpoint:
    auditevents:
      enabled: true 
imss:
  firma-electronica:
    base-url: ${SIDEIMSS_FIRMA_DIGITAL:http://172.16.23.224}  # https://firmadigitalssl.imss.gob.mx # Esta será la parte base     http://172.16.23.224 
