server:
  port: ${SIDEIMSS_DOCUMENTOS_PORT}
jwt:
  secret: TExBVkVfTVVZX1NFQ1JFVEzE3Zmxu7BSGSJx72BSBXM 
spring:
  application:
    name: mssideimss-documentos
management:
  endpoints:
    web:
      base-path: /mssideimss-documentos/v1/actuator
      exposure:
        include: health
  endpoint:
    auditevents:
      enabled: true
    
hadoop:
  username: ${HADOOP_USER_NAME_ENV:kioimss} 
  default-fs: ${HADOOP_DEFAULT_FS_ENV:hdfs://10.104.24.3:9000}  